### ISSUE TITLE
Provide ability to set custom headers for caching purposes

### ISSUE THREAD

**Issue by venil7** [keen/keen-analysis.js#10]
I'd like to be able to set custom headers on all outgoing requests, to provide my proxy to cache these requests

**Comment by dustinlarimer** [comment]
@venil7 great suggestion, I'd be more than happy to expose a `headers` method to the request chain that lets you set/get an object containing the header values to be used. 

I imagine it would work like this:

```javascript
client
  .post('YOUR_PROXY_URL')
  .headers({
    // define custom header values here
  })
  .send({
    event_collection: 'pageviews',
    timeframe: 'this_14_days'
  })
  .then(function(res){
    // do something with the result
  })
  .catch(function(err){
    // catch and handle errors
  });
```

How does that look?

**Comment by venil7** [comment]
yes, that's exactly what I'm expecting, great!
