### ISSUE TITLE
Cached Datasets

### ISSUE THREAD

**Issue by jtfell** [keen/keen-analysis.js#20]
I have a use case that would fit cached datasets perfectly. The problem is that I'm using the keen-analysis library and need to keep the cached dataset usage in sync with the queries run ad-hoc (as some custom logic will operate on both sets of results). Therefore I need to reuse the `Keen.Query` declarations to define some cached datasets.

My questions:

  a) Is there any cached dataset support in keen-analysis or is it planned in the near future?
  b) If there isn't, can I get some pointers on how to go about adding it that would be likely to be merged?

**Comment by dustinlarimer** [comment]
@jtfell your patch has been published and deployed as `v1.3.0` -- thanks again for your help 👍

**Comment by jtfell** [comment]
Cheers @dustinlarimer - looking forward to taking it for a spin!
