### ISSUE TITLE
Filter timeframe with saved query

### ISSUE THREAD

**Issue by jcampbell05** [keen/keen-analysis.js#42]
Is there a way of reducing the timeframe for a saved query? So if the query is for 14 days can I ask the library to filter it down to 7 days like I can for a cached dataset.

**Comment by adamkasprowicz** [comment]
Hi @jcampbell05 !
You're more than welcome to join our slack channel to ask questions and get answers faster 
https://keen-community.slack.com
Regarding your question:
It's possible, but only if you are using Interval and Extraction query. Then you may use https://github.com/keen/keen-analysis.js#local-queries to filter the results.
Personally, I would use multiple saved queries with different timeframes.
