### ISSUE TITLE
HTTP methods exposed by the keenClient should return the http status code

### ISSUE THREAD

**Issue by raul-handpoint** [keen/keen-analysis.js#44]
When using the http methods of the keenClient, the response object should include the http response code.

This information can be helpful, for example, to find out if a cached dataset or a cached query was created, updated or deleted successfully through the API.

**Comment by adamkasprowicz** [comment]
Hi Raul, thank you for the suggestion

What about .catch? All of the responses with statuses different than 200, 201, 204 may be handled with catch. If there's something missing - can you describe a situation where it isn't working properly?

Here's an example:

```javascript
client
  .put({
    url: client.url('queries', 'saved', 'daily-pageviews-this-14-days'),
    api_key: client.config.masterKey,
    params: {
      refresh_rate: 60 * 60 * 4,
      query: {
        analysis_type: 'count',
        event_collection: 'pageviews',
        timeframe: 'this_14_days'
      },
      metadata: {
        display_name: 'Daily pageviews (this 14 days)',
        visualization: {
          chart_type: "metric"
        }
      }
    }
  }).then(res => {
    console.log('ok', res);
  }).catch(e => {
    console.log('error', e);
  });
```
