### ISSUE TITLE
External dependencies should not be bundled in the localQuery module

### ISSUE THREAD

**Issue by stof** [keen/keen-analysis.js#54]
As the dependencies (on `moment` and a few others) are declared in the package.json, they should not be bundled in the file (at least for the `node` output) but be treated as externals instead.
This way, bundlers like webpack or rollup would import them from their location and be able to dedupe them. When they are bundled, they don't know about the fact that most of the code is actually from `moment`.

**Comment by stof** [comment]
@maciejrybaniec why closing this without any comment ?

**Comment by maciejrybaniec** [comment]
To be done as part of [performance](https://github.com/keen/keen/issues/37) epic.

**Comment by stof** [comment]
That performance epic seems to have been closed without being done
