### ISSUE TITLE
Bundle files should be optimized

### ISSUE THREAD

**Issue by stof** [keen/keen-analysis.js#55]
When using webpack or rollup, the `dist/node/keen-analysis.js` file is used.

But this file is built with webpack in development mode, and so without the ModuleConcatenationPlugin. This has a big impact on the file size, and that's not something that webpack can optimize later (it does not have optimizations able to recognize a bundle generated by webpack to re-optimize it later).

**Comment by stof** [comment]
Note that this is also not friendly to tree-shaking, as it is performed only for ES modules.

Providing a build output as ESM would help a lot for that (still transpiled with babel to account for common configurations which are not running babel on node_modules, probably). But that one would require switching the build tool to rollup, as webpack is not able to do that for now (it does not support ES modules as an output format).

**Comment by adamkasprowicz** [comment]
Hi @stof,
Thank you for all of the great suggestions! We'll add these issues to our backlog.
Regards

**Comment by stof** [comment]
any news on that ?

**Comment by stof** [comment]
@maciejrybaniec why closing this without any answer ?

**Comment by maciejrybaniec** [comment]
Hi @stof as mentioned in previous [comment](https://github.com/keen/keen-analysis.js/issues/56) . 

From my point of view in modern javascript world all of projects should support tree-shaking and different targets - and this will be addressed as a part of [performance](https://github.com/keen/keen/issues/37) epic.
