### ISSUE TITLE
Polyfills should be loaded separately

### ISSUE THREAD

**Issue by stof** [keen/keen-analysis.js#56]
It would be great if a build bundle could be provided with no polyfills included (I'm thinking about the Promise and fetch polyfill here). We could have a file including polyfills and the other entrypoint to create a full bundle for easy consumption (or polyfills can be always expected externally, but that would require a major version bump).
In my project, I'm already loading polyfills for them, so it makes no sense to load them again when loading keen-analysis. That only increase the size of the JS.

**Comment by stof** [comment]
@maciejrybaniec what is the state of this ? Is it done or is it closed as "won't fix" ?

**Comment by maciejrybaniec** [comment]
@stof Hi, we are in the process of cleaning and creating a new backlog as well as migrating keen-analysis to mono-repository (https://github.com/keen/keen) to provide a better quality of our projects.

The performance / bundle size's are a very large topic in contexts of all already existing projects in our space - and it's on our new roadmap.

From my point of view the polyfills should be extracted from main bundle and delivered as optional separate bundle. I created a separate [epic](https://github.com/keen/keen/issues/37) in mono-repository for better visibility.

**Comment by stof** [comment]
> From my point of view the polyfills should be extracted from main bundle and delivered as optional separate bundle.

totally agree with that (my project already loads such polyfills).
A solution I saw elsewhere is to document the list of necessary polyfills, and include the appropriate https://polyfill.io/ URL in the readme for people wanting to use this tool to load them easily.

**Comment by stof** [comment]
https://github.com/keen/keen/issues/37 has been marked as completed in 2020, however keen-analysis.js still bundles a promise polyfill in its main bundle (and maybe other polyfills as well)
