### ISSUE TITLE
include metadata config option

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-analysis.js#59]
if you initialize our lib with

```
const client = new KeenAnalysis({
  projectId: 'YOUR_PROJECT_ID',
  readKey: 'YOUR_READ_KEY',
  includeMetadata: true,
});
```

the response of each of the queries that you'll run should contain metadata informations

**Comment by adamkasprowicz** [comment]
scenario:
I create a new keen-analysis instance. I create 10 different queries to the API. If I want to get metadata info for each of the queries - I need to write over and over again `includeMetadata: true` inside each `client.query(`
Let's introduce more `global` option, defined in the constructor of the keen-analysis instance.

**Comment by apryka** [comment]
released in https://github.com/keen/keen-analysis.js/releases/tag/v3.4.4
