### ISSUE TITLE
two queries at the same time

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-analysis.js#61]
```If make two keen-analysis.js queries at the same time, one which has sortBy+groupBy+interval, and the other which just has groupBy, the keen-analysis library seems to mix up the "options" for the two requests and parse one or the other incorrectly and crash.```

**Comment by michieldewilde** [comment]
@adamkasprowicz is there any solution for this at the moment?

**Comment by maciejrybaniec** [comment]
Hi, @michieldewilde. Right now we are re-organizing our products road map - I'll move this ticket to backlog with higher priority. 

My suggestion for now - for environment different than browser is to use `Promise.all` on single client queries.

**Comment by michieldewilde** [comment]
We are using GraphQL so we have no control over the way that these queries are being executed and  of the queries.
All queries are being ran in parallel.
I have tried to instantiate a new client for every query but most likely this is a singleton and it keeps failing for that reason.
Hope that a fix is coming out soon.

**Comment by maciejrybaniec** [comment]
@michieldewilde 
As we are during process of migration to mono-repository - I created a ticket there for better tracking and visibility (https://github.com/keen/keen/issues/65).

In next week we start a new iteration and I'll make sure that the issue will be added to the scope and addressed.

**Comment by maciejrybaniec** [comment]
@michieldewilde We are planning to publish a release candidate version in this week. 
We'll be very grateful if You could check if applied changed solves the issue on Your side.

**Comment by michieldewilde** [comment]
@maciejrybaniec I will certainly try the new fixes. Thank you for the timely fix.

**Comment by apryka** [comment]
@michieldewilde Please try with `npm i keen-analysis@3.4.7-rc.0`

**Comment by michieldewilde** [comment]
will do

**Comment by apryka** [comment]
released in https://github.com/keen/keen-analysis.js/releases/tag/v3.5.0
