### ISSUE TITLE
@types/keen-analysis not found

### ISSUE THREAD

**Issue by martin-garcia-blanco** [keen/keen-analysis.js#84]
Working with React in TypeScript, the application doesn't understand the types so webpack recommend me to install the library. This problem appears when I try to import keen-analysis

```
import KeenAnalysis from 'keen-analysis';
```

```
Could not find a declaration file for module 'keen-analysis'. '/Users/../Projects/envoy/.../node_modules/keen-analysis/dist/node/keen-analysis.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/keen-analysis` if it exists or add a new declaration (.d.ts) file containing `declare module 'keen-analysis';`
```

So I tried to install @types/keen-analysis, but npm says that this library doesn't exist? are there any library to type keen-analysis?

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fkeen-analysis - Not found
npm ERR! 404 
npm ERR! 404  '@types/keen-analysis@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by maciejrybaniec** [comment]
Hi @martin-garcia-blanco,

Currently there are no dedicated typings for keen-analysis - as far as I know there are no plans in current roadmap to create @types/keen-analysis package.

To avoid the problem with
```
Could not find a declaration file for module 'keen-analysis'
```
Please, create a `index.d.ts` file in `typings/keen-analysis` directory and make sure Your `tsconfig.json` file respects this path.

Insert inside `index.d.ts` :
```
declare module 'keen-analysis';
```

**Comment by martin-garcia-blanco** [comment]
Hi Maciej, thanks for answer as quick

Create this file generates the following error
```
declare module 'keen-analysis';
```

```
Invalid module name in augmentation. Module 'keen-analysis' resolves to an untyped module at '/Users/.../Projects/.../.../node_modules/keen-analysis/dist/node/keen-analysis.js', which cannot be augmented.
```

**Comment by martin-garcia-blanco** [comment]
Sorry Maciej you were right I was putting the declaration in another file, and that generates de error I posted before.
Again thanks for your quick response!

**Comment by martin-garcia-blanco** [comment]
Now the problem is that jest is throwing an error trying to import the library, I would appreciate whatever hint

```

    Jest encountered an unexpected token

    This usually means that you are trying to import a file that Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/martingarciablanco/Projects/envoy/dashboard-front/node_modules/@keen.io/widgets/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { legendSettings, widgetSettings } from './widget-settings';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { FunnelChartWidget } from '@keen.io/widgets';
        | ^
      2 | import KeenAnalysis from 'keen-analysis';
      3 | import React, { useEffect, useState } from 'react';
      4 | import './styles.css';

```

**Comment by mczapkowicz** [comment]
Hi @martin-garcia-blanco,

It looks like jest uses not transformed version of this module. 

Looking at the one of possible solutions:

> „To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.”

You can use **transformIgnorePatterns** in your _jest.config_ to specify that these files should be transformed by jest:

```
transformIgnorePatterns: [
     "<rootDir>/node_modules/(?!(@keen.io)/)"
],
```
which means: "Ignore everything in node_modules except for @keen.io"

**Comment by martin-garcia-blanco** [comment]
Thanks again KeenIO team, 
The solution works well. For my side we can close the issue although I think put this information in some readme could help to other typescript devs 😃.

Best regards Martin.

**Comment by maciejrybaniec** [comment]
@martin-garcia-blanco we are glad that we could help :)
Thank You for the suggestions - we'll add additional information in our docs.

Best regards 
Maciej
